name: First Workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches:
      - main
      - 'dev-*'
    branches-ignore:
      - 'test/**'
    tags:
      - front-end
    paths:
      - '.src/**'
    paths-ignore:
      - '.github/workflows/*'    
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
              echo "Hello world"
              echo "from me!"
      - name: Print goodbye
        run: echo "Bye!"
