name: First Workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
              echo "Hello world"
              echo "from me!"
      - name: Print goodbye
        run: echo "Bye!"
